export const stateList = [
    {id: "ak", value: "Alaska"},
    {id: "ar", value: "Arkansas"},
    {id: "az", value: "Arizona"},
    {id: "ca", value: "California"},
    {id: "co", value: "Colorado"},
    {id: "fl", value: "Florida"},
    {id: "hi", value: "Hawaii"},
    {id: "id", value: "Idaho"},
    {id: "ky", value: "Kentucky"},
    {id: "in", value: "Indiana"},
    {id: "me", value: "Maine"},
    {id: "mi", value: "Michigan"},
    {id: "mn", value: "Minnesota"},
    {id: "mo", value: "Missouri"},
    {id: "mt", value: "Montana"},
    {id: "nv", value: "Nevada"},
    {id: "nm", value: "New Mexico"},
    {id: "nd", value: "North Dakota"},
    {id: "nc", value: "North Carolina"},
    {id: "oh", value: "Ohio"},
    {id: "or", value: "Oregon"},
    {id: "sc", value: "South Carolina"},
    {id: "sd", value: "South Dakota"},
    {id: "tn", value: "Tennessee"},
    {id: "tx", value: "Texas"},
    {id: "ut", value: "Utah"},
    {id: "va", value: "Virginia"},
    {id: "wa", value: "Washington"},
    {id: "wv", value: "West Virginia"},
    {id: "wy", value: "Wyoming"}
  ]
